### ISSUE TITLE
Skalierungsfehler in Mobile-Darstellung

### ISSUE THREAD

**Issue by philippgeisler** [okfde/storyhunt.de#1]
zwei kleine Skalierungsfehler im mobilen Layout (Portrait) der Website (Safari für iOS, iPhone5s):

- OKF DE Logo nahezu nicht sichtbar
- Hintergrundbilder skalieren nicht richtig wodurch a) Bild wie Pixelbrei aussieht und b) Titel der Seite nicht vollständig sichtbar ist

![img_3470](https://cloud.githubusercontent.com/assets/3661582/25994038/891a6a66-370c-11e7-9b10-a2cb9cfee9e0.PNG)

**Comment by seegerseeger** [comment]
Danke für den Hinweis, ist nun fixed.
